### PR TITLE
added ability for Gen 2 devices to backup and restore scripts

### PR DESCRIPTION
**Pull request by Beat2er**
I decided to stay with the json implementation, so I put the code of the scripts inside json objects. (this made the reuse of `backupJsons` possible, resulting in only one point of loading the data)

### CODE REVIEW

**Comment by Beat2er** [comment]
wonderful project by the way. I just had a small look into it, but great cover of all major function

**Comment by usnasoft** [comment]
good poin but this update would break the existing upload from backup file; see:
it.usna.shellyscan.view.scripts.ScriptsPanel.loadCodeFromFile(File, Script)

I sudgest to modify the return type of:
it.usna.shellyscan.controller.RestoreAction.readBackupFile(File)
into  Map<String, Object> or encapsulate here the script into a json Object leaving
it.usna.shellyscan.model.device.g2.AbstractBatteryG2Device.backup(File)
as it is

Question: what appens if a script with the same name alredy exists? Maybe is safer to restore only if no scipt is stored on the device?

I also think that it would probably be safer to disable by default any imported script

**Comment by Beat2er** [comment]
Hi, I will have a look at the first point in the next couple of days, but I didn't notice this function.

I think the concept would be, that if you restore the device, it get's restored to (if possible) exactly the same state as before, including activated scripts. There would be the option of renaming (restored_<scriptname>) new scripts, if one already exists and not enabling, even if it was enabled on backup. What is you opinion on that?
Nevertheless I will rework my code to not break `it.usna.shellyscan.view.scripts.ScriptsPanel.loadCodeFromFile(File, Script)`.

You will hear from me in the next following days.

**Comment by usnasoft** [comment]
> I think the concept would be, that if you restore the device, it get's restored to (if possible) exactly the same state as before, including activated scripts. There would be the option of renaming (restored_) new scripts, if one already exists and not enabling, 

good idea; and also "restored_2_" if "restored_" exists and so on ...

a message should clearly be displayed to warn the user, this could easily be implemented on 
it.usna.shellyscan.model.device.ShellyAbstractDevice.restoreCheck(Map<String, JsonNode>)
but this will not be possible for "deferred restores" (it.usna.shellyscan.controller.RestoreAction) or a new return message system must be implemented (currently any return message from restore is treated as an error.

By the way, I will now merge my dev branch to main to minimize conflicts

**Comment by Beat2er** [comment]
Let me have a 2nd look again before you spend your time looking over this please

**Comment by Beat2er** [comment]
I reworked it and only modified the loading part specific to the restore, to not break anything else.
I also added conditional messages prompting the user if script was enabled or does already exist (see images, ignore german please ;))
Screenshot 2024-02-03 215749
Screenshot 2024-02-03 215735

- We have a potential edge case of trying to enable more than 3 (for my test device, didn't find anything adhoc online documenting that) scripts. But I would ignore this here, as this problem exists in more places and is only a minor factor, that might possibly be changed with future releases.
grafik

**Comment by Beat2er** [comment]
Ok, have a look at it please. (Be kind please xD)
I force-pushed, as the revision was too far away from the first commit.

**Review by usnasoft — APPROVED** [review]

**Comment by usnasoft** [comment]
I'm now merging, I think I will modify the code so that any imported script will be not enabled

**Comment by usnasoft** [comment]
good job!

**Comment by Beat2er** [comment]
Thanks, this was my first contribution to a open source project.
The user is asked, if he wants to enable any of the restored scripts (if any was enabled at backup time). So this change should already be accounted for.

**Comment by usnasoft** [comment]
I hope to see more valuable contributes from you. Finally I did some minor modifications:
- inverted "override" logic on GUI: rename is now the default option;
- no restore of "enable" flag allowed if rename is selected ("sc" & "sc_restored" probably should not be both enabled)

**Pull request merged**
